sonar.projectKey=ismailcherri_merge-pro
sonar.organization=ismailcherri
sonar.projectName=MergePro
sonar.javascript.lcov.reportPaths=coverage/node/lcov.info,coverage/webview/lcov.info
sonar.testExecutionReportPaths=coverage/node/test-report.xml,coverage/webview/test-report.xml
sonar.sources=src,webview
sonar.tests=test
sonar.test.exclusions=test/integration/**
